// <auto-generated/>
#pragma warning disable CS0618
using Farkle.ApiClient.Api.Games.Item.Players.Item.Keeps;
using Farkle.ApiClient.Api.Games.Item.Players.Item.Rolls;
using Farkle.ApiClient.Api.Games.Item.Players.Item.Turns;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Farkle.ApiClient.Api.Games.Item.Players.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \api\games\{gameId}\players\{playerId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithPlayerItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The keeps property</summary>
        public global::Farkle.ApiClient.Api.Games.Item.Players.Item.Keeps.KeepsRequestBuilder Keeps
        {
            get => new global::Farkle.ApiClient.Api.Games.Item.Players.Item.Keeps.KeepsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The rolls property</summary>
        public global::Farkle.ApiClient.Api.Games.Item.Players.Item.Rolls.RollsRequestBuilder Rolls
        {
            get => new global::Farkle.ApiClient.Api.Games.Item.Players.Item.Rolls.RollsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The turns property</summary>
        public global::Farkle.ApiClient.Api.Games.Item.Players.Item.Turns.TurnsRequestBuilder Turns
        {
            get => new global::Farkle.ApiClient.Api.Games.Item.Players.Item.Turns.TurnsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Farkle.ApiClient.Api.Games.Item.Players.Item.WithPlayerItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithPlayerItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/games/{gameId}/players/{playerId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Farkle.ApiClient.Api.Games.Item.Players.Item.WithPlayerItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithPlayerItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/games/{gameId}/players/{playerId}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
