// <auto-generated/>
#pragma warning disable CS0618
using Farkle.ApiClient.Api.Games.Item.Players;
using Farkle.ApiClient.Api.Games.Item.Start;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Farkle.ApiClient.Api.Games.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \api\games\{gameId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithGameItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The players property</summary>
        public global::Farkle.ApiClient.Api.Games.Item.Players.PlayersRequestBuilder Players
        {
            get => new global::Farkle.ApiClient.Api.Games.Item.Players.PlayersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The start property</summary>
        public global::Farkle.ApiClient.Api.Games.Item.Start.StartRequestBuilder Start
        {
            get => new global::Farkle.ApiClient.Api.Games.Item.Start.StartRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Farkle.ApiClient.Api.Games.Item.WithGameItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithGameItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/games/{gameId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Farkle.ApiClient.Api.Games.Item.WithGameItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithGameItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/games/{gameId}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
