// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebApp.ReadModel;

#nullable disable

namespace WebApp.Migrations.ReadModel
{
    [DbContext(typeof(ReadModelDbContext))]
    partial class ReadModelDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebApp.ReadModel.GameView", b =>
                {
                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<long>("Position")
                        .HasColumnType("bigint");

                    b.Property<string>("StateJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("GameId");

                    b.ToTable("GameViews");
                });

            modelBuilder.Entity("WebApp.ReadModel.SubscriptionCheckpoint", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long?>("Position")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Checkpoints");
                });
#pragma warning restore 612, 618
        }
    }
}
