// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Farkle.ApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class FarkleContractsHttpResponses_GameStateResponse : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The currentPlayerId property</summary>
        public int? CurrentPlayerId { get; set; }
        /// <summary>The diceKept property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<int?>? DiceKept { get; set; }
#nullable restore
#else
        public List<int?> DiceKept { get; set; }
#endif
        /// <summary>The diceSetAside property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<int?>? DiceSetAside { get; set; }
#nullable restore
#else
        public List<int?> DiceSetAside { get; set; }
#endif
        /// <summary>The gameId property</summary>
        public int? GameId { get; set; }
        /// <summary>The hostPlayerId property</summary>
        public int? HostPlayerId { get; set; }
        /// <summary>The scoreboard property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Farkle.ApiClient.Models.FarkleContractsHttpResponses_PlayerScore>? Scoreboard { get; set; }
#nullable restore
#else
        public List<global::Farkle.ApiClient.Models.FarkleContractsHttpResponses_PlayerScore> Scoreboard { get; set; }
#endif
        /// <summary>The stage property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Stage { get; set; }
#nullable restore
#else
        public string Stage { get; set; }
#endif
        /// <summary>The tableCenter property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<int?>? TableCenter { get; set; }
#nullable restore
#else
        public List<int?> TableCenter { get; set; }
#endif
        /// <summary>The turnNumber property</summary>
        public int? TurnNumber { get; set; }
        /// <summary>The turnScore property</summary>
        public int? TurnScore { get; set; }
        /// <summary>The winner property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Farkle.ApiClient.Models.FarkleContractsHttpResponses_WinnerResponse? Winner { get; set; }
#nullable restore
#else
        public global::Farkle.ApiClient.Models.FarkleContractsHttpResponses_WinnerResponse Winner { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Farkle.ApiClient.Models.FarkleContractsHttpResponses_GameStateResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Farkle.ApiClient.Models.FarkleContractsHttpResponses_GameStateResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Farkle.ApiClient.Models.FarkleContractsHttpResponses_GameStateResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "currentPlayerId", n => { CurrentPlayerId = n.GetIntValue(); } },
                { "diceKept", n => { DiceKept = n.GetCollectionOfPrimitiveValues<int?>()?.AsList(); } },
                { "diceSetAside", n => { DiceSetAside = n.GetCollectionOfPrimitiveValues<int?>()?.AsList(); } },
                { "gameId", n => { GameId = n.GetIntValue(); } },
                { "hostPlayerId", n => { HostPlayerId = n.GetIntValue(); } },
                { "scoreboard", n => { Scoreboard = n.GetCollectionOfObjectValues<global::Farkle.ApiClient.Models.FarkleContractsHttpResponses_PlayerScore>(global::Farkle.ApiClient.Models.FarkleContractsHttpResponses_PlayerScore.CreateFromDiscriminatorValue)?.AsList(); } },
                { "stage", n => { Stage = n.GetStringValue(); } },
                { "tableCenter", n => { TableCenter = n.GetCollectionOfPrimitiveValues<int?>()?.AsList(); } },
                { "turnNumber", n => { TurnNumber = n.GetIntValue(); } },
                { "turnScore", n => { TurnScore = n.GetIntValue(); } },
                { "winner", n => { Winner = n.GetObjectValue<global::Farkle.ApiClient.Models.FarkleContractsHttpResponses_WinnerResponse>(global::Farkle.ApiClient.Models.FarkleContractsHttpResponses_WinnerResponse.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("currentPlayerId", CurrentPlayerId);
            writer.WriteCollectionOfPrimitiveValues<int?>("diceKept", DiceKept);
            writer.WriteCollectionOfPrimitiveValues<int?>("diceSetAside", DiceSetAside);
            writer.WriteIntValue("gameId", GameId);
            writer.WriteIntValue("hostPlayerId", HostPlayerId);
            writer.WriteCollectionOfObjectValues<global::Farkle.ApiClient.Models.FarkleContractsHttpResponses_PlayerScore>("scoreboard", Scoreboard);
            writer.WriteStringValue("stage", Stage);
            writer.WriteCollectionOfPrimitiveValues<int?>("tableCenter", TableCenter);
            writer.WriteIntValue("turnNumber", TurnNumber);
            writer.WriteIntValue("turnScore", TurnScore);
            writer.WriteObjectValue<global::Farkle.ApiClient.Models.FarkleContractsHttpResponses_WinnerResponse>("winner", Winner);
        }
    }
}
#pragma warning restore CS0618
