// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Farkle.ApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class JoinPlayerResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The currentPlayerId property</summary>
        public int? CurrentPlayerId { get; set; }
        /// <summary>The hostPlayerId property</summary>
        public int? HostPlayerId { get; set; }
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>The roster property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Farkle.ApiClient.Models.LobbyPlayer>? Roster { get; set; }
#nullable restore
#else
        public List<global::Farkle.ApiClient.Models.LobbyPlayer> Roster { get; set; }
#endif
        /// <summary>The stage property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Stage { get; set; }
#nullable restore
#else
        public string Stage { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Farkle.ApiClient.Models.JoinPlayerResponse"/> and sets the default values.
        /// </summary>
        public JoinPlayerResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Farkle.ApiClient.Models.JoinPlayerResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Farkle.ApiClient.Models.JoinPlayerResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Farkle.ApiClient.Models.JoinPlayerResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "currentPlayerId", n => { CurrentPlayerId = n.GetIntValue(); } },
                { "hostPlayerId", n => { HostPlayerId = n.GetIntValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "roster", n => { Roster = n.GetCollectionOfObjectValues<global::Farkle.ApiClient.Models.LobbyPlayer>(global::Farkle.ApiClient.Models.LobbyPlayer.CreateFromDiscriminatorValue)?.AsList(); } },
                { "stage", n => { Stage = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("currentPlayerId", CurrentPlayerId);
            writer.WriteIntValue("hostPlayerId", HostPlayerId);
            writer.WriteIntValue("id", Id);
            writer.WriteCollectionOfObjectValues<global::Farkle.ApiClient.Models.LobbyPlayer>("roster", Roster);
            writer.WriteStringValue("stage", Stage);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
