// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Farkle.ApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PassTurnResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The currentPlayerId property</summary>
        public int? CurrentPlayerId { get; set; }
        /// <summary>The gameId property</summary>
        public int? GameId { get; set; }
        /// <summary>The newScore property</summary>
        public int? NewScore { get; set; }
        /// <summary>The playerId property</summary>
        public int? PlayerId { get; set; }
        /// <summary>The scoreboard property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Farkle.ApiClient.Models.PlayerScore>? Scoreboard { get; set; }
#nullable restore
#else
        public List<global::Farkle.ApiClient.Models.PlayerScore> Scoreboard { get; set; }
#endif
        /// <summary>The turnNumber property</summary>
        public int? TurnNumber { get; set; }
        /// <summary>The winner property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Farkle.ApiClient.Models.PassTurnResponse.PassTurnResponse_winner? Winner { get; set; }
#nullable restore
#else
        public global::Farkle.ApiClient.Models.PassTurnResponse.PassTurnResponse_winner Winner { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Farkle.ApiClient.Models.PassTurnResponse"/> and sets the default values.
        /// </summary>
        public PassTurnResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Farkle.ApiClient.Models.PassTurnResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Farkle.ApiClient.Models.PassTurnResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Farkle.ApiClient.Models.PassTurnResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "currentPlayerId", n => { CurrentPlayerId = n.GetIntValue(); } },
                { "gameId", n => { GameId = n.GetIntValue(); } },
                { "newScore", n => { NewScore = n.GetIntValue(); } },
                { "playerId", n => { PlayerId = n.GetIntValue(); } },
                { "scoreboard", n => { Scoreboard = n.GetCollectionOfObjectValues<global::Farkle.ApiClient.Models.PlayerScore>(global::Farkle.ApiClient.Models.PlayerScore.CreateFromDiscriminatorValue)?.AsList(); } },
                { "turnNumber", n => { TurnNumber = n.GetIntValue(); } },
                { "winner", n => { Winner = n.GetObjectValue<global::Farkle.ApiClient.Models.PassTurnResponse.PassTurnResponse_winner>(global::Farkle.ApiClient.Models.PassTurnResponse.PassTurnResponse_winner.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("currentPlayerId", CurrentPlayerId);
            writer.WriteIntValue("gameId", GameId);
            writer.WriteIntValue("newScore", NewScore);
            writer.WriteIntValue("playerId", PlayerId);
            writer.WriteCollectionOfObjectValues<global::Farkle.ApiClient.Models.PlayerScore>("scoreboard", Scoreboard);
            writer.WriteIntValue("turnNumber", TurnNumber);
            writer.WriteObjectValue<global::Farkle.ApiClient.Models.PassTurnResponse.PassTurnResponse_winner>("winner", Winner);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Farkle.ApiClient.Models.PassTurnResponse_winnerMember1"/>, <see cref="global::Farkle.ApiClient.Models.WinnerResponse"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class PassTurnResponse_winner : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Farkle.ApiClient.Models.PassTurnResponse_winnerMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Farkle.ApiClient.Models.PassTurnResponse_winnerMember1? PassTurnResponseWinnerMember1 { get; set; }
#nullable restore
#else
            public global::Farkle.ApiClient.Models.PassTurnResponse_winnerMember1 PassTurnResponseWinnerMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Farkle.ApiClient.Models.WinnerResponse"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Farkle.ApiClient.Models.WinnerResponse? WinnerResponse { get; set; }
#nullable restore
#else
            public global::Farkle.ApiClient.Models.WinnerResponse WinnerResponse { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Farkle.ApiClient.Models.PassTurnResponse.PassTurnResponse_winner"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Farkle.ApiClient.Models.PassTurnResponse.PassTurnResponse_winner CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::Farkle.ApiClient.Models.PassTurnResponse.PassTurnResponse_winner();
                if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.PassTurnResponseWinnerMember1 = new global::Farkle.ApiClient.Models.PassTurnResponse_winnerMember1();
                }
                else if("WinnerResponse".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.WinnerResponse = new global::Farkle.ApiClient.Models.WinnerResponse();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(PassTurnResponseWinnerMember1 != null)
                {
                    return PassTurnResponseWinnerMember1.GetFieldDeserializers();
                }
                else if(WinnerResponse != null)
                {
                    return WinnerResponse.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(PassTurnResponseWinnerMember1 != null)
                {
                    writer.WriteObjectValue<global::Farkle.ApiClient.Models.PassTurnResponse_winnerMember1>(null, PassTurnResponseWinnerMember1);
                }
                else if(WinnerResponse != null)
                {
                    writer.WriteObjectValue<global::Farkle.ApiClient.Models.WinnerResponse>(null, WinnerResponse);
                }
            }
        }
    }
}
#pragma warning restore CS0618
