// <auto-generated />
using System;
using Farkle.Infrastructure.ReadModel;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Farkle.Infrastructure.Migrations.ReadModel
{
    [DbContext(typeof(ReadModelDbContext))]
    [Migration("20260626043302_FeedbackViewReadModel")]
    partial class FeedbackViewReadModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Farkle.Infrastructure.ReadModel.FeedbackView", b =>
                {
                    b.Property<long>("Position")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("GameId")
                        .HasColumnType("integer");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<string>("Route")
                        .HasColumnType("text");

                    b.Property<string>("Sentiment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Stage")
                        .HasColumnType("text");

                    b.HasKey("Position");

                    b.HasIndex("GameId");

                    b.ToTable("FeedbackViews");
                });

            modelBuilder.Entity("Farkle.Infrastructure.ReadModel.GameView", b =>
                {
                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<long>("Position")
                        .HasColumnType("bigint");

                    b.Property<string>("StateJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("GameId");

                    b.ToTable("GameViews");
                });

            modelBuilder.Entity("Farkle.Infrastructure.ReadModel.SubscriptionCheckpoint", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long?>("Position")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Checkpoints");
                });
#pragma warning restore 612, 618
        }
    }
}
