<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Ardalis.Result" Version="10.1.0" />
      <PackageReference Include="Eventuous.AspNetCore" Version="0.15.0-beta.7" />
      <PackageReference Include="FastEndpoints" Version="8.1.0" />
      <PackageReference Include="Mapster" Version="10.0.7" />
    </ItemGroup>

</Project>
