// <auto-generated/>
#pragma warning disable CS0618
using HotDice.ApiClient.Api.Auth;
using HotDice.ApiClient.Api.Feedback;
using HotDice.ApiClient.Api.Games;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace HotDice.ApiClient.Api
{
    /// <summary>
    /// Builds and executes requests for operations under \api
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ApiRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The auth property</summary>
        public global::HotDice.ApiClient.Api.Auth.AuthRequestBuilder Auth
        {
            get => new global::HotDice.ApiClient.Api.Auth.AuthRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The feedback property</summary>
        public global::HotDice.ApiClient.Api.Feedback.FeedbackRequestBuilder Feedback
        {
            get => new global::HotDice.ApiClient.Api.Feedback.FeedbackRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The games property</summary>
        public global::HotDice.ApiClient.Api.Games.GamesRequestBuilder Games
        {
            get => new global::HotDice.ApiClient.Api.Games.GamesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::HotDice.ApiClient.Api.ApiRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ApiRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::HotDice.ApiClient.Api.ApiRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ApiRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
