<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Farkle.Spa</RootNamespace>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Ardalis.Result" Version="8.0.0" />
    <PackageReference Include="Ardalis.SmartEnum" Version="8.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="8.0.4" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="8.0.4" PrivateAssets="all" />
    <PackageReference Include="MudBlazor" Version="6.19.1" />
  </ItemGroup>

  <ItemGroup>
    <_ContentIncludedByDefault Remove="wwwroot\css\bootstrap\bootstrap.min.css"/>
    <_ContentIncludedByDefault Remove="wwwroot\css\bootstrap\bootstrap.min.css.map"/>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Services\IGameService.cs">
      <DependentUpon>GameService.cs</DependentUpon>
    </Compile>
    <Compile Update="Services\IRotationCalculator.cs">
      <DependentUpon>RotationCalculator.cs</DependentUpon>
    </Compile>
    <Compile Update="Services\CommandResponse.cs">
      <DependentUpon>GameService.cs</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Farkle.Contracts\Farkle.Contracts.csproj" />
  </ItemGroup>
</Project>
